### ISSUE TITLE
Where can I find the code for weak supervision?

### ISSUE THREAD

**Issue by ybc-ybc** [wu-zhonghua/RAC-Net#2]
Hello, congratulations on your great work!

Where can I find the code for weak supervision?   I haven't seen it yet.

Thank you very much, looking forward to your reply!

**Comment by Wjy0316** [comment]
I have the same problem as you, have you solved it yet? If so can you teach me about it? Thank you for your help.

**Comment by Wjy0316** [comment]
> Hello, congratulations on your great work!
> 
> Where can I find the code for weak supervision? I haven't seen it yet.
> 
> Thank you very much, looking forward to your reply!

I have the same problem as you, have you solved it yet? If so can you teach me about it? Thank you for your help.

**Comment by ybc-ybc** [comment]
> > Hello, congratulations on your great work!
> > Where can I find the code for weak supervision? I haven't seen it yet.
> > Thank you very much, looking forward to your reply!
> 
> I have the same problem as you, have you solved it yet? If so can you teach me about it? Thank you for your help.

https://github.com/wu-zhonghua/RAC-Net/blob/main/pcr/engines/defaults.py

**Comment by Wjy0316** [comment]
> > > Hello, congratulations on your great work!
> > > Where can I find the code for weak supervision? I haven't seen it yet.
> > > Thank you very much, looking forward to your reply!
> > 
> > 
> > I have the same problem as you, have you solved it yet? If so can you teach me about it? Thank you for your help.
> 
> https://github.com/wu-zhonghua/RAC-Net/blob/main/pcr/engines/defaults.py

Thank you for your reply.
Are you saying that the use of pseudo-tags in this code is partly a reflection of weak supervision?
I have another question to ask you now, I didn't find the part of this code that uses the OTOC weakly supervised labeling approach, I hope you can point it out for me if you can.Thank you.

**Comment by ybc-ybc** [comment]
> > > > Hello, congratulations on your great work!
> > > > Where can I find the code for weak supervision? I haven't seen it yet.
> > > > Thank you very much, looking forward to your reply!
> > > 
> > > 
> > > I have the same problem as you, have you solved it yet? If so can you teach me about it? Thank you for your help.
> > 
> > 
> > https://github.com/wu-zhonghua/RAC-Net/blob/main/pcr/engines/defaults.py
> 
> Thank you for your reply. Are you saying that the use of pseudo-tags in this code is partly a reflection of weak supervision? I have another question to ask you now, I didn't find the part of this code that uses the OTOC weakly supervised labeling approach, I hope you can point it out for me if you can.Thank you.

I'm sorry, I'm not sure about those details, either.

**Comment by Wjy0316** [comment]
> > > > > Hello, congratulations on your great work!
> > > > > Where can I find the code for weak supervision? I haven't seen it yet.
> > > > > Thank you very much, looking forward to your reply!
> > > > 
> > > > 
> > > > I have the same problem as you, have you solved it yet? If so can you teach me about it? Thank you for your help.
> > > 
> > > 
> > > https://github.com/wu-zhonghua/RAC-Net/blob/main/pcr/engines/defaults.py
> > 
> > 
> > Thank you for your reply. Are you saying that the use of pseudo-tags in this code is partly a reflection of weak supervision? I have another question to ask you now, I didn't find the part of this code that uses the OTOC weakly supervised labeling approach, I hope you can point it out for me if you can.Thank you.
> 
> I'm sorry, I'm not sure about those details, either.

**Thanks for the reply and good luck with everything.**
